// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhwrrTz7hu1kpiZOUGGDRmrX-kBRKP6eI',
    appId: '1:173102596800:web:2e97c9f06e39da6156e325',
    messagingSenderId: '173102596800',
    projectId: 'audiovideo-70863',
    authDomain: 'audiovideo-70863.firebaseapp.com',
    storageBucket: 'audiovideo-70863.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8ZlqTje4HdIHBaX5taummFdogFfWTi1s',
    appId: '1:173102596800:android:6b73aec8c598990d56e325',
    messagingSenderId: '173102596800',
    projectId: 'audiovideo-70863',
    storageBucket: 'audiovideo-70863.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxEza1pQRMuHicXmW1DoR0SklglTGPq3M',
    appId: '1:173102596800:ios:c427dee4d117f71c56e325',
    messagingSenderId: '173102596800',
    projectId: 'audiovideo-70863',
    storageBucket: 'audiovideo-70863.firebasestorage.app',
    iosBundleId: 'com.example.webrtcFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiAGjW_pKYXz7ZCI2yVQ47rVOoDc6X4vw',
    appId: '1:173102596800:web:8f3a526774576e6f56e325',
    messagingSenderId: '173102596800',
    projectId: 'audiovideo-70863',
    authDomain: 'audiovideo-70863.firebaseapp.com',
    storageBucket: 'audiovideo-70863.firebasestorage.app',
  );
}
